version: '3.3'

services:
    wordpress:
      container_name: wordpress
      build: ./wordpress
      restart: always
      env_file:
        - .env
      volumes:
        - wordpress:/var/www/html/
      networks:
        - inception
      depends_on:
        - mariadb
      expose: 
        - "9000"

    nginx:
      container_name: nginx
      build: ./nginx
      restart: always
      volumes: 
        - wordpress:/var/www/html
      networks:
        - inception
      depends_on:
        - wordpress
      ports:
        - "443:443"
        - "80:80"
    mariadb:
      container_name: mariadb
      build: ./mariadb
      env_file:
        - .env
      restart: always
      networks:
        - inception
      expose:
        - "3306"
      volumes:
        - db:/var/lib/mysql

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      device: /home/${USER}/data/WordPress
      o: bind
      type: none
  db:
    driver: local
    driver_opts:
      device: /home/${USER}/data/DB
      o: bind
      type: none