version: '3.8'

services:
    wordpress:
      container_name: wordpress
      build: ./wordpress
      restart: always
      volumes:
        - wordpress_vol:/var/www/html/
      networks:
        - inception
      depends_on:
        - mariadb
      expose: 
        - "9000"

    nginx:
      container_name: nginx
      build: ./nginx
      restart: always
      volumes: 
        - wordpress_vol:/var/www/html
      networks:
        - inception
      depends_on:
        - wordpress
      ports:
        - "443:443"
    mariadb:
      container_name: mariadb
      build: ./mariadb
      restart: always
      networks:
        - inception
      expose:
        - "3306"

networks:
  inception:
    driver: bridge

volumes:
  wordpress_vol:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: /home/data/wordpress
    #   o: bind